### ISSUE TITLE
Panic when removing first element from empty vector

### ISSUE THREAD

**Issue by qarmin** [gsuyemoto/onvif-client-rs#2]
Code from example  - https://github.com/gsuyemoto/onvif-cam-rs?tab=readme-ov-file#getting-started

panics
 
```
thread 'main' panicked at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/onvif-cam-rs-0.2.1/src/builder/camera.rs:51:60:
removal index (is 0) should be < len (is 0)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/core/src/panicking.rs:74:14
   2: alloc::vec::Vec<T,A>::remove::assert_failed
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/alloc/src/vec/mod.rs:1636:13
   3: alloc::vec::Vec<T,A>::remove
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/alloc/src/vec/mod.rs:1641:13
   4: onvif_cam_rs::builder::camera::CameraBuilder::set_device_info::{{closure}}
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/onvif-cam-rs-0.2.1/src/builder/camera.rs:51:43
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/core/src/future/future.rs:123:9
   6: <onvif_cam_rs::device::camera::Camera as onvif_cam_rs::builder::camera::CameraBuilder>::build_all::{{closure}}
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/onvif-cam-rs-0.2.1/src/device/camera.rs:22:91
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/core/src/future/future.rs:123:9
   8: untitled::main::{{closure}}
             at ./src/main.rs:16:28
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:63
  10: tokio::runtime::coop::with_budget
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:363:45
  18: tokio::runtime::runtime::Runtime::block_on
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
  19: untitled::main
             at ./src/main.rs:14:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/4ac7bcbaad8d6fd7a51bdf1b696cbc3ba4c796cf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
in
```
        let mut result             = DeviceInfo::default(); 
        result.firmware_version    = Some(firmware_version.remove(0));
        result.serial_num          = Some(serial_number.remove(0));
        result.hardware_id         = Some(hardware_id.remove(0));
        result.model               = Some(model.remove(0));
        result.manufacturer        = Some(manufacturer.remove(0));
```

**Comment by zuckschwerdt** [comment]
It should be e.g.
`        result.firmware_version    = firmware_version.into_iter().next();`
